[package]
name = "lua"
version = "0.1.4"
description = "Lua is a lightweight, multi-paradigm programming language designed primarily for embedded use in applications"
readme = "README.md"
repository = "https://github.com/wapm-packages/lua"

[[module]]
name = "lua"
source = "lua.wasm"
abi = "emscripten"

[[command]]
name = "lua"
module = "lua"
